version: '3'
services:

  auth-db:
    image: postgres:11
    container_name: auth-db
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432


  sales-db:
    image: mongo
    container_name: sales_rabbit
    networks:
      - sales-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=sales
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
      - 28017:28017
  
  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales-db
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
  
  # product-api:
  #   image: product-api
  #   container_name: product-api
  #   environment:
  #     - API_SECRET=YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=
  #     - PRODUCT_EXCHANGE=product.topic
  #     - PRODUCT_STOCK_ROUTING_KEY=product-stock-update.routingKey
  #     - SALES_CONFIRMATION_ROUTING_KEY=sales-confirmation.routingKey
  #     - PRODUCT_STOCK_QUEUE=product-stock-update.queue
  #     - SALES_CONFIRMATION_QUEUE=sales-confirmation.queue

  #   ports:
  #     - 8081:8081

    # product-api:
    #   image: product-api
    #   container_name: product-api
    #   depends_on:
    #     - product-db
    #     - sales_rabbit
    #   networks:
    #     - sales-network
    #   environment:
    #     - PORT=8081
    #     - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
    #     - DB_HOST=product-db
    #     - DB_NAME=product-db
    #     - DB_USER=admin
    #     - DB_PASSWORD=123456
    #     - DB_PORT=5432
    #     - RABBIT_MQ_HOST=sales_rabbit
    #     - RABBIT_MQ_PORT=5672
    #     - RABBIT_MQ_USER=guest
    #     - RABBIT_MQ_PASSWORD=guest
    #     - SALES_HOST=sales-api
    #     - SALES_PORT=8082

    #   ports:
    #     - 8081:8081

networks:
  sales-network:
    driver: bridge
